"""Convert a completed Chinese salesperson annotation CSV into JSONL.

The input is expected to be exported from Feishu / Excel using the Chinese
columns generated by ``build_salesperson_annotation_pack_v2.py``.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from piwm_data.annotation_act_terms import CN_TO_EN_ACT, EN_TO_CN_ACT, OPERATIONAL_5ACTS


ACT_ZH_TO_EN = CN_TO_EN_ACT
STAGE_ZH_TO_EN = {
    "刚注意到商品/设备": "attention",
    "开始感兴趣/浏览比较": "interest",
    "已经有明确倾向": "desire",
    "准备购买/确认": "action",
    "attention": "attention",
    "interest": "interest",
    "desire": "desire",
    "action": "action",
}
DECISION_ZH_TO_EN = {
    "应该介入": "go",
    "不应该介入": "no-go",
    "不确定": "uncertain",
}
ACT_ORDER = list(OPERATIONAL_5ACTS)
ACT_SCORE_COLUMNS = {
    act: (f"{EN_TO_CN_ACT[act]}适合度(1-5)", f"{EN_TO_CN_ACT[act]}不适合原因(≤2时填写)")
    for act in ACT_ORDER
}


def clean(value: Any) -> str | None:
    if value is None:
        return None
    text = str(value).strip()
    return text or None


def parse_int(value: Any) -> int | None:
    text = clean(value)
    if text is None:
        return None
    try:
        return int(float(text))
    except ValueError:
        return None


def split_multi(value: Any) -> list[str]:
    text = clean(value)
    if not text:
        return []
    for sep in ["；", ";", "、", ",", "，", "|"]:
        text = text.replace(sep, "|")
    return [item.strip() for item in text.split("|") if item.strip() and item.strip() != "无"]


def load_holdout(path: Path | None) -> dict[str, dict[str, Any]]:
    if not path:
        return {}
    rows: dict[str, dict[str, Any]] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.strip():
            row = json.loads(line)
            rows[row["sample_id"]] = row
    return rows


def act_from_zh(value: Any) -> str | None:
    text = clean(value)
    if not text:
        return None
    return ACT_ZH_TO_EN.get(text, text if text in ACT_ORDER else None)


def stage_from_zh(value: Any) -> str | None:
    text = clean(value)
    if not text:
        return None
    return STAGE_ZH_TO_EN.get(text, text)


def decision_from_zh(value: Any) -> str | None:
    text = clean(value)
    if not text:
        return None
    return DECISION_ZH_TO_EN.get(text, text)


def build_act_ratings(row: dict[str, str]) -> list[dict[str, Any]]:
    ratings: list[dict[str, Any]] = []
    for act in ACT_ORDER:
        score_col, reason_col = ACT_SCORE_COLUMNS[act]
        ratings.append(
            {
                "act": act,
                "suitability": parse_int(row.get(score_col)),
                "reason_if_low": clean(row.get(reason_col)),
            }
        )
    return ratings


def second_best_act(ratings: list[dict[str, Any]], primary_act: str | None) -> str | None:
    scored = [
        (rating["suitability"], -ACT_ORDER.index(rating["act"]), rating["act"])
        for rating in ratings
        if rating["suitability"] is not None and rating["act"] != primary_act
    ]
    if not scored:
        return None
    return max(scored)[2]


def convert_row(row: dict[str, str], holdout: dict[str, dict[str, Any]]) -> dict[str, Any]:
    sample_id = clean(row.get("样本ID"))
    if not sample_id:
        raise ValueError("row missing 样本ID")
    hidden = holdout.get(sample_id, {})
    primary_act = act_from_zh(row.get("你认为最合适的主动作"))
    secondary_acts = [ACT_ZH_TO_EN.get(item, item) for item in split_multi(row.get("这句话还顺带包含哪些目的"))]
    ratings = build_act_ratings(row)
    annotator_stage = stage_from_zh(row.get("你判断顾客所处阶段"))
    system_stage = hidden.get("system_stage_label")

    decomposition = []
    for idx in range(1, 4):
        text = clean(row.get(f"话术片段{idx}"))
        act = act_from_zh(row.get(f"片段{idx}对应目的"))
        if text or act:
            decomposition.append({"text": text, "act": act})

    return {
        "task_id": sample_id,
        "video_frames": [clean(row.get("第1张图")), clean(row.get("第2张图")), clean(row.get("第3张图"))],
        "scene_context": clean(row.get("场景描述")),
        "hidden_labels_not_shown_to_annotator": {
            "system_stage_label": system_stage,
            "system_intent_label": hidden.get("system_intent_label"),
            "system_best_act": hidden.get("system_best_act"),
            "dataset_split": hidden.get("dataset_split") or "target_5act_test",
        },
        "annotator": {
            "annotator_id": clean(row.get("标注员ID")),
            "tenure_years": parse_int(row.get("销售经验年限")),
            "annotation_date": clean(row.get("标注日期")),
            "annotation_duration_seconds": None,
        },
        "observation": {
            "visible_cues": split_multi(row.get("你看到的顾客信号")),
            "customer_state_judgment": clean(row.get("你判断顾客现在的状态")),
            "annotator_stage_judgment": annotator_stage,
            "stage_judgment_confidence": parse_int(row.get("阶段判断确定度(1-5)")),
            "stage_agreement_with_system": None if not system_stage or not annotator_stage else system_stage == annotator_stage,
            "stage_disagreement_reason": clean(row.get("阶段判断补充说明")),
        },
        "go_no_go": {
            "decision": decision_from_zh(row.get("现在是否应该主动介入")),
            "reason": clean(row.get("为什么现在应该/不应该介入")),
            "urgency": parse_int(row.get("介入紧迫程度(1-5)")),
        },
        "best_intervention": {
            "primary_act": primary_act,
            "secondary_act_tags": secondary_acts,
            "confidence": parse_int(row.get("主动作判断确定度(1-5)")),
            "utterance": clean(row.get("如果介入，你第一句话会怎么说")),
            "utterance_goal_type": clean(row.get("这句话的主要目的")),
            "utterance_act_decomposition": decomposition,
        },
        "act_ratings": ratings,
        "counterfactual_reasoning": {
            "second_best_act": second_best_act(ratings, primary_act),
            "why_not_second_best": clean(row.get("为什么不选择第二合适做法")),
        },
        "expected_customer_reaction": {
            "likely_next_state": clean(row.get("你预计顾客接下来会怎么反应")),
            "positive_signal_expected": clean(row.get("你认为的正向信号")),
            "negative_signal_expected": clean(row.get("你认为的负向信号")),
        },
        "annotation_meta": {
            "annotation_difficulty": parse_int(row.get("这条难不难标(1-5)")),
            "data_quality_concern": clean(row.get("图片/视频有没有质量问题")),
            "needs_discussion": clean(row.get("是否需要讨论")) in {"是", "需要", "true", "True", "1"},
            "notes": clean(row.get("备注")),
        },
    }


def run(args: argparse.Namespace) -> dict[str, Any]:
    holdout = load_holdout(args.holdout)
    rows_out: list[dict[str, Any]] = []
    with args.input.open(encoding=args.encoding, newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            if clean(row.get("样本ID")):
                rows_out.append(convert_row(row, holdout))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8") as handle:
        for row in rows_out:
            handle.write(json.dumps(row, ensure_ascii=False, sort_keys=True) + "\n")
    return {"input": str(args.input), "output": str(args.output), "rows": len(rows_out)}


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, required=True, help="CSV exported from Feishu or Excel.")
    parser.add_argument("--output", type=Path, required=True, help="Output JSONL path.")
    parser.add_argument("--holdout", type=Path, default=None, help="Optional theory_labels_holdout.jsonl.")
    parser.add_argument("--encoding", default="utf-8-sig")
    return parser


def main() -> None:
    print(json.dumps(run(build_parser().parse_args()), ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
